# .air.toml
# Configuración para forzar a air a usar el comando de compilación que sabemos que funciona.

root = "."
tmp_dir = "tmp"

[build]
# Comando exacto para compilar el proyecto.
cmd = "go build -o ./tmp/main ."
# Binario que se ejecutará después de la compilación.
bin = "tmp/main"
# Archivo de log para errores de compilación.
log = "tmp/build-errors.log"

[misc]
# Limpiar el directorio temporal al salir.
clean_on_exit = true
